name: frontend
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  chopper: ^6.1.2
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # use flutter analyze to run linter
  flutter_lints: ^2.0.1
  # dart run build_runner build
  build_runner:
  flutter_launcher_icons: ^0.12.0
  chopper_generator: ^6.0.1
  json_serializable: ^6.6.1
  # flutter pub run build_runner build -> builds the openapi based parts
  swagger_dart_code_generator: ^2.11.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
