name: frontend
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  chopper: ^6.1.2
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  equatable: ^2.0.5
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  # use flutter analyze to run linter
  flutter_lints: ^2.0.1
  # dart run build_runner build
  build_runner:
  flutter_launcher_icons: ^0.12.0
  chopper_generator: ^6.0.1
  json_serializable: ^6.6.1
  # flutter pub run build_runner build -> builds the openapi based parts
  swagger_dart_code_generator: ^2.11.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBoldItalic.ttf
          style: italic
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900

